[package]
name = "seqcol_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
noodles-sam = "0.54.0"

[dependencies]
base64 = "0.22.0"
sha2 = { version = "0.10.8", features = ["asm", "asm-aarch64"] }
